Pakwheels scraper
A-ASAD/scrapy pull request #1
Opened 2021-08-05 15:49 UTC by A-ASAD

Scraps Name, Price, and Description of newly launched cars from Pakwheels.com.

2021-08-10 09:55 UTC, saadyousafarbi requested changes
There are some comments I have added, please have a look!

Please write the results to a CSV file, instead of only printing them out.

2021-08-10 09:55 UTC, saadyousafarbi commented on pakwheels/pakwheels/spiders/github_spider.py
> +                'password': ''
Get these from environment variables!

2021-08-10 09:55 UTC, saadyousafarbi commented on pakwheels/pakwheels/spiders/github_spider.py
> +        repositories = ', '.join(map(str.strip, repositories))
use xpath selectors for the github crawler

2021-08-10 09:55 UTC, saadyousafarbi commented on pakwheels/pakwheels/spiders/pakwheels_spider.py
> +                yield scrapy.Request(url=url, callback=self.parse_used_cars)
you should have the same callback method for handling response. In the callback method, you can have a different method for used and new cars!

2021-08-10 09:55 UTC, saadyousafarbi commented on pakwheels/pakwheels/spiders/github_spider.py
> +            'https://github.com/A-ASAD?tab=repositories',
the username here needs to come from the username, should not be hardcoded!

2021-08-10 17:07 UTC, A-ASAD commented on pakwheels/pakwheels/spiders/github_spider.py
> +            'https://github.com/A-ASAD?tab=repositories',
I've explored all the page and retraced javascript requests, I'm unable to get the username from the dashboard. So, I'll have to hard code it here.

2021-08-12 08:42 UTC, AhtishamShahid commented on pakwheels/pakwheels/middlewares.py
> +        s = cls()
Use a more descriptive name.

2021-08-12 08:42 UTC, AhtishamShahid commented on pakwheels/pakwheels/middlewares.py
> +        for i in result:
same here , use more descriptive naming.

2021-08-12 08:42 UTC, AhtishamShahid commented on pakwheels/pakwheels/spiders/github_spider.py
> +        name = response.xpath(
These can be moved in different functions.

2021-08-12 10:14 UTC, A-ASAD commented on pakwheels/pakwheels/middlewares.py
> +        s = cls()
This is an auto-generated file having some default implementation for middleware.

2021-08-12 10:15 UTC, A-ASAD commented on pakwheels/pakwheels/middlewares.py
> +        for i in result:
This is an auto-generated file having some default implementation for middleware.

2021-08-17 11:34 UTC, merged